name: APNS
options:
  deploymentTarget:
    macOS: "13.0"
packages: {}
targets:
  APNS:
    type: application
    platform: macOS
    sources:
      - path: Sources
    info:
      path: Info.plist
    entitlements:
      path: APNS.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.APNS
      SWIFT_VERSION: 5.9
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_ENTITLEMENTS: APNS.entitlements
    scheme: {} 